### ISSUE TITLE
Not able to work with moat-mqtt

### ISSUE THREAD

**Issue by didimelli** [M-o-a-T/moat-mqtt#15]
Hello,

I have always worked with Distmqtt with no issue.
Today I tried to install moat-mqtt for a new project and I am not able to work with it.

I have a new python 3.8 project, and i use poetry.
I just installed moat-mqtt (3.6.1 is the only one available on PyPI)

```sh
poetry new asd
cd asd
poetry add moat-mqtt
```

![image](https://user-images.githubusercontent.com/53627721/191969542-771ebcab-b75e-4357-be14-c2d73480acd7.png)

and the installation is correct
![image](https://user-images.githubusercontent.com/53627721/191969713-c818491e-e618-4abb-a16f-f6b66318c12a.png)

and I definitely see distmqtt in the venv directory
![image](https://user-images.githubusercontent.com/53627721/191971820-188f95a2-0c3b-4e67-8232-827e0dc787bc.png)

However, there is no way for me to import or use moat-mqtt.

```python
from moat.mqtt.mqtt.constants import QOS_1
from moat.mqtt.mqtt.constants import QOS_2

print(QOS_1, QOS_2)
```
Running this (`poetry run python asd/__init__.py`) gives me:
```
Traceback (most recent call last):
  File "asd/__init__.py", line 1, in <module>
    from moat.mqtt.mqtt.constants import QOS_1
ModuleNotFoundError: No module named 'moat'
```

Am I missing something obvious or is the new version with the new naming not supposed to be used yet?

Thank you!

**Comment by smurfix** [comment]
I have uploaded 0.38.2. My builder didn't auto-upload, oops …

I'm sorry that the transition isn't as seamless as we all would like; I'm building the tools to automate much of this as I go along. Please don't hesitate to complain if anything doesn't work yet.

**Comment by didimelli** [comment]
Awesome, with this new version everything is working properly, thanks!!
